### ISSUE TITLE
做个人站？

### ISSUE THREAD

**Issue by liu316484231** [easychen/howto-make-more-money#16]
rt

**Comment by huanghe2015** [comment]
难。捐款别想；付费阅读被支付卡住；广告被插件卡住。

**Comment by easychen** [comment]
> 难。捐款别想；付费阅读被支付卡住；广告被插件卡住。

对个人支付接口  https://github.com/easychen/howto-make-more-money#%E5%8F%AF%E7%94%A8%E6%94%AF%E4%BB%98%E6%8E%A5%E5%8F%A3
