### ISSUE TITLE
请问录教学视频,如何能快速生成普通话字幕呢? 感谢!

### ISSUE THREAD

**Issue by zhaoolee** [easychen/howto-make-more-money#17]

**Comment by ydcool** [comment]
很多平台都有类似的字幕听写工具。语音识别后生成文本或者带有时间信息的 srt 字幕文件。再自己通过后期制作进去就好了。

**Comment by zhaoolee** [comment]
> 很多平台都有类似的字幕听写工具。语音识别后生成文本或者带有时间信息的 srt 字幕文件。再自己通过后期制作进去就好了。

gosubtitle比较好用, 但免费版限制一分钟, 有推荐的平台么?

**Comment by ydcool** [comment]
很久之前用过网易见外，挺不错的。最近没关注，不知道是不是收费了。科大讯飞，百度等可能都有类似服务。

**Comment by zhaoolee** [comment]
> 很久之前用过网易见外，挺不错的。最近没关注，不知道是不是收费了。科大讯飞，百度等可能都有类似服务。

网易见外真的惨
![image](https://user-images.githubusercontent.com/15868458/70957056-cd108900-20af-11ea-8f38-d8e5fff6f44c.png)

**Comment by easychen** [comment]
以前是用网易见外，最近好像不能用了。

arctime 也支持语音生成字幕 https://arctime.org/auto-speech-recognition.html

另外好像人人也出了一个平台 https://www.1sj.tv/html/AINotice/index.html?version=1576550730000
