### ISSUE TITLE
Translate to English

### ISSUE THREAD

**Issue by ngarawakimani** [easychen/howto-make-more-money#22]
This repo is trending for a reason, am sure many of us would benefit from it if it had an English translation.

Chinese developers please think of us (who do not understand chinese language but would really benefit from your repos).

**Comment by Siricee** [comment]
Agree with you. 

Github, as a **platform without borders**, should have an English README as least. 
If you just release Chinese version, Why not publish on Gitee? 

**Respect to developers all over the world does always matter.**

**Comment by easychen** [comment]
> Agree with you.
> 
> Github, as a **platform without borders**, should have an English README as least.
> If you just release Chinese version, Why not publish on Gitee?
> 
> **Respect to developers all over the world does always matter.**
> 
> _If the repo is not applicable to situation to countries outside of China, A Notice in English ,reminds that ‘the repo is not applicable to foreigners’, to people who are not Chinese should be required._

There is . 
![Uploading Screen Shot 2020-02-06 at 15.56.52.png…]()

**Comment by easychen** [comment]
> This repo is trending for a reason, am sure many of us would benefit from it if it had an English translation.
> 
> Chinese developers please think of us (who do not understand chinese language but would really benefit from your repos).

This article is about how programmers earn pocket money in China. Most of the services mentioned require a Chinese mobile phone number to register. So I don't think translation into English makes much sense. Maybe I can write a separate English article in the future.
