### ISSUE TITLE
按需雇用真的适合副业吗？

### ISSUE THREAD

**Issue by ngzhio** [easychen/howto-make-more-money#28]
通常一个处于 996 周期的程序员，在下班后已经累得半死，也没有多少休闲时间了，这时还要从一个“长工”变为一个“短工”，跑到另一个雇主那里打工，这个投入产出比能有多高？

**Comment by easychen** [comment]
> 通常一个处于 996 周期的程序员，在下班后已经累得半死，也没有多少休闲时间了，这时还要从一个“长工”变为一个“短工”，跑到另一个雇主那里打工，这个投入产出比能有多高？

首先，这不是写给996的程序员的书。
然后，996就别折腾了，命要紧。

**Comment by tangchen2004** [comment]
国外的小伙伴比较适合
