### ISSUE TITLE
星星评分的正反向调整

### ISSUE THREAD

**Issue by jhygreatbug** [easychen/howto-make-more-money#31]
![image](https://user-images.githubusercontent.com/6092159/78883756-82ff4900-7a8c-11ea-9fd1-c221be844b1a.png)

建议调整评分的标准的正负向。

投入——投入越低，评分越高
产出——产出越高，评分越高
持久性——越持久，评分越高
风险——风险越低，评分越高
门槛——门槛越低，评分越高

这样阅读时可以只看星星数量，数量越多，代表该资产在这一项评价上更占优

**Comment by easychen** [comment]
感谢建议，最近版本已经调整。
