### ISSUE TITLE
在线 gitbook 不支持一些 emoji 表情

### ISSUE THREAD

**Issue by euxx** [easychen/howto-make-more-money#36]
发现一个小问题，在线 gitbook 不支持一些 emoji 表情，比如 [15 章](http://r.ftqq.com/howto-make-more-money/ch15.html) 最后的表情 🤣 显示为 ‘[]’

**Comment by easychen** [comment]
那个应该是你用的设备或者系统不支持，我用 Mac 看是正常的。以后想想怎么优化下吧。

**Comment by euxx** [comment]
确实是，之前用的是 Ubuntu 16，试了下手机上也是正常的=
