### ISSUE TITLE
奇奇怪怪的邮件

### ISSUE THREAD

**Issue by ycdxsb** [easychen/howto-make-more-money#41]
我也不知道这个邮件是谁发的，我明明没有star也没有fork这个项目

<img width="652" alt="image-20210705094130990" src="https://user-images.githubusercontent.com/32149596/124406990-5e6c4c80-dd75-11eb-9bcd-8a21144267f5.png">

**Comment by lany1721** [comment]
你Watch了

**Comment by ycdxsb** [comment]
> 你Watch了

好吧，确实看过这个项目，你也收到这个了吗？

**Comment by 252860883** [comment]
同收到，这咋还骂人呢

**Comment by DanRan-hcy** [comment]
有毛病

**Comment by PurpleSwords** [comment]
一大波人在赶来的路上

**Comment by DanRan-hcy** [comment]
全军出击

**Comment by bamboo-pan** [comment]
大家make money了没？😃



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Dinosaur- ***@***.***&gt;
发送时间: 2021年7月5日 09:48
收件人: easychen/howto-make-more-money ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[easychen/howto-make-more-money] 奇奇怪怪的邮件 (#41)





 
同收到，这咋还骂人呢

**Comment by MarcusJr** [comment]
没毛病，这咋还骂人呢
________________________________
发件人: PurpleSwords ***@***.***>
发送时间: Monday, July 5, 2021 9:49:41 AM
收件人: easychen/howto-make-more-money ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [easychen/howto-make-more-money] 奇奇怪怪的邮件 (#41)


一大波人在赶来的路上

―

**Comment by 623059008** [comment]
别随便发邮件，有很多人会收到的。这个是用来通知项目变动的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月5日(周一) 上午9:47
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [easychen/howto-make-more-money] 奇奇怪怪的邮件 (#41)




 
同收到，这咋还骂人呢

**Comment by 0x219** [comment]
我要取消watch了😒

**Comment by XieJiale-china** [comment]
哥，发给我干嘛




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "easychen/howto-make-more-money"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月5日(星期一) 上午9:50
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [easychen/howto-make-more-money] 奇奇怪怪的邮件 (#41)





 大家make money了没？😃 
 
 
 
 发自我的iPhone 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: Dinosaur- ***@***.***&amp;gt; 
 发送时间: 2021年7月5日 09:48 
 收件人: easychen/howto-make-more-money ***@***.***&amp;gt; 
 抄送: Subscribed ***@***.***&amp;gt; 
 主题: 回复：[easychen/howto-make-more-money] 奇奇怪怪的邮件 (#41) 
 
 
 
 
 
   
 同收到，这咋还骂人呢

**Comment by DanRan-hcy** [comment]
> 我要取消watch了😒

同操作

**Comment by XieJiale-china** [comment]
+1




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月5日(星期一) 上午9:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [easychen/howto-make-more-money] 奇奇怪怪的邮件 (#41)





  
我要取消watch了😒
  
同操作

**Comment by fengsheng-v** [comment]
能不能搞个权限

**Comment by AnotherJ1** [comment]
一大群吃瓜群众

**Comment by 252860883** [comment]
试一下改成这样的 watch 就可以了：
![image](https://user-images.githubusercontent.com/26960215/124407559-cec79d80-dd76-11eb-84db-930937a24e07.png)

**Comment by borankux** [comment]
谁不想赚点钱呢 😏
